### ISSUE TITLE
Dataset??

### ISSUE THREAD

**Issue by advith-jet** [vignatej/House-price-prediction#1]
Can I please know which dataset you have used for this project.
 I tried to replicated this project. But, I couldn't find the exact dataset.

**Comment by vignatej** [comment]
Hi @advith-jet , glad you tried to replicate this project. 
The dataset I used is "Housing prediction dataset". Its famously open-sourced. 
But new version of dataset is released. I did use one of previous versions of the dataset.
you can use any version of dataset. It doesn't matter.
Link: [Dataset Link](https://www.kaggle.com/datasets/yasserh/housing-prices-dataset)
